apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: how2die-forward-http-to-https
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`how2die.com`, `{subdomain:[a-z]+}.how2die.com`)
    kind: Rule
    services:
    - name: traefik-ingress-controller-http-service
      port: 80
    middlewares:
    - name: redirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: how2die-website-ingress
  namespace: default
spec:
  entryPoints:
  - web-secure
  routes:
  - match: Host(`how2die.com`)
    kind: Rule
    services:
    - name: website
      port: 80
  tls:
    certResolver: default

---
# ------------------- Middlewares ------------------- #

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
