---
# ------------------- Namespace: traefik ------------------- #

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.how2die.com
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-dashboard
          servicePort: 8080

---
# ------------------- Namespace: kube-system ------------------- #

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k8s.how2die.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
          
---
# ------------------- Namespace: default ------------------- #

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: how2die-website-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: how2die.com
    http: &http_rules # YAML id
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 80
      - path: /api/messages
        backend:
          serviceName: message-server
          servicePort: 8080
  - host: www.how2die.com
    http: *http_rules
  - host: jenkins.how2die.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
  - host: sql.how2die.com
    http:
      paths:
      - path: /
        backend:
          serviceName: adminer
          servicePort: 8080
