---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
  namespace: traefik
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]

    # Accept invalid SSL certificates for backends
    insecureSkipVerify = true

    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

      [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$zjjGWKW4$W2JIcu4m26WzOzzESDF0W/"]

    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "traefik/traefik-ingress-controller-http-service"

    [ping]
    entryPoint = "http"

    [api]
    entryPoint = "traefik"

    [acme]
    email = "admin@how2die.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

    [[acme.domains]]
      main = "how2die.com"
      sans = ["www.how2die.com", "k8s.how2die.com"]
