---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]

    # Accept invalid SSL certificates for backends
    insecureSkipVerify = true    
    
    # Entrypoints definition
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    # Enable retry sending request if network error
    [retry]

    # ACME (Let's Encrypt) configuration
    [acme]
    email = "admin@how2die.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true

    [acme.tlsChallenge]

    [[acme.domains]]
      main = "how2die.com"
      sans = ["www.how2die.com", "k8s.how2die.com", "sql.how2die.com", "jenkins.how2die.com"]
